<?php

namespace Database\Seeders;

use App\Models\Province;
use Carbon\Carbon;

use Illuminate\Database\Seeder;

class ProvincesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $currentTimestamp = Carbon::now();

        $provinces = [
            ['pro_id' => '0101', 'pro_nombre' => 'Chachapoyas', 'dep_id' => '01'],
            ['pro_id' => '0102', 'pro_nombre' => 'Bagua', 'dep_id' => '01'],
            ['pro_id' => '0103', 'pro_nombre' => 'Bongará', 'dep_id' => '01'],
            ['pro_id' => '0104', 'pro_nombre' => 'Condorcanqui', 'dep_id' => '01'],
            ['pro_id' => '0105', 'pro_nombre' => 'Luya', 'dep_id' => '01'],
            ['pro_id' => '0106', 'pro_nombre' => 'Rodríguez de Mendoza', 'dep_id' => '01'],
            ['pro_id' => '0107', 'pro_nombre' => 'Utcubamba', 'dep_id' => '01'],
            ['pro_id' => '0201', 'pro_nombre' => 'Huaraz', 'dep_id' => '02'],
            ['pro_id' => '0202', 'pro_nombre' => 'Aija', 'dep_id' => '02'],
            ['pro_id' => '0203', 'pro_nombre' => 'Antonio Raymondi', 'dep_id' => '02'],
            ['pro_id' => '0204', 'pro_nombre' => 'Asunción', 'dep_id' => '02'],
            ['pro_id' => '0205', 'pro_nombre' => 'Bolognesi', 'dep_id' => '02'],
            ['pro_id' => '0206', 'pro_nombre' => 'Carhuaz', 'dep_id' => '02'],
            ['pro_id' => '0207', 'pro_nombre' => 'Carlos Fermín Fitzcarrald', 'dep_id' => '02'],
            ['pro_id' => '0208', 'pro_nombre' => 'Casma', 'dep_id' => '02'],
            ['pro_id' => '0209', 'pro_nombre' => 'Corongo', 'dep_id' => '02'],
            ['pro_id' => '0210', 'pro_nombre' => 'Huari', 'dep_id' => '02'],
            ['pro_id' => '0211', 'pro_nombre' => 'Huarmey', 'dep_id' => '02'],
            ['pro_id' => '0212', 'pro_nombre' => 'Huaylas', 'dep_id' => '02'],
            ['pro_id' => '0213', 'pro_nombre' => 'Mariscal Luzuriaga', 'dep_id' => '02'],
            ['pro_id' => '0214', 'pro_nombre' => 'Ocros', 'dep_id' => '02'],
            ['pro_id' => '0215', 'pro_nombre' => 'Pallasca', 'dep_id' => '02'],
            ['pro_id' => '0216', 'pro_nombre' => 'Pomabamba', 'dep_id' => '02'],
            ['pro_id' => '0217', 'pro_nombre' => 'Recuay', 'dep_id' => '02'],
            ['pro_id' => '0218', 'pro_nombre' => 'Santa', 'dep_id' => '02'],
            ['pro_id' => '0219', 'pro_nombre' => 'Sihuas', 'dep_id' => '02'],
            ['pro_id' => '0220', 'pro_nombre' => 'Yungay', 'dep_id' => '02'],
            ['pro_id' => '0301', 'pro_nombre' => 'Abancay', 'dep_id' => '03'],
            ['pro_id' => '0302', 'pro_nombre' => 'Andahuaylas', 'dep_id' => '03'],
            ['pro_id' => '0303', 'pro_nombre' => 'Antabamba', 'dep_id' => '03'],
            ['pro_id' => '0304', 'pro_nombre' => 'Aymaraes', 'dep_id' => '03'],
            ['pro_id' => '0305', 'pro_nombre' => 'Cotabambas', 'dep_id' => '03'],
            ['pro_id' => '0306', 'pro_nombre' => 'Chincheros', 'dep_id' => '03'],
            ['pro_id' => '0307', 'pro_nombre' => 'Grau', 'dep_id' => '03'],
            ['pro_id' => '0401', 'pro_nombre' => 'Arequipa', 'dep_id' => '04'],
            ['pro_id' => '0402', 'pro_nombre' => 'Camaná', 'dep_id' => '04'],
            ['pro_id' => '0403', 'pro_nombre' => 'Caravelí', 'dep_id' => '04'],
            ['pro_id' => '0404', 'pro_nombre' => 'Castilla', 'dep_id' => '04'],
            ['pro_id' => '0405', 'pro_nombre' => 'Caylloma', 'dep_id' => '04'],
            ['pro_id' => '0406', 'pro_nombre' => 'Condesuyos', 'dep_id' => '04'],
            ['pro_id' => '0407', 'pro_nombre' => 'Islay', 'dep_id' => '04'],
            ['pro_id' => '0408', 'pro_nombre' => 'La Uniòn', 'dep_id' => '04'],
            ['pro_id' => '0501', 'pro_nombre' => 'Huamanga', 'dep_id' => '05'],
            ['pro_id' => '0502', 'pro_nombre' => 'Cangallo', 'dep_id' => '05'],
            ['pro_id' => '0503', 'pro_nombre' => 'Huanca Sancos', 'dep_id' => '05'],
            ['pro_id' => '0504', 'pro_nombre' => 'Huanta', 'dep_id' => '05'],
            ['pro_id' => '0505', 'pro_nombre' => 'La Mar', 'dep_id' => '05'],
            ['pro_id' => '0506', 'pro_nombre' => 'Lucanas', 'dep_id' => '05'],
            ['pro_id' => '0507', 'pro_nombre' => 'Parinacochas', 'dep_id' => '05'],
            ['pro_id' => '0508', 'pro_nombre' => 'Pàucar del Sara Sara', 'dep_id' => '05'],
            ['pro_id' => '0509', 'pro_nombre' => 'Sucre', 'dep_id' => '05'],
            ['pro_id' => '0510', 'pro_nombre' => 'Víctor Fajardo', 'dep_id' => '05'],
            ['pro_id' => '0511', 'pro_nombre' => 'Vilcas Huamán', 'dep_id' => '05'],
            ['pro_id' => '0601', 'pro_nombre' => 'Cajamarca', 'dep_id' => '06'],
            ['pro_id' => '0602', 'pro_nombre' => 'Cajabamba', 'dep_id' => '06'],
            ['pro_id' => '0603', 'pro_nombre' => 'Celendín', 'dep_id' => '06'],
            ['pro_id' => '0604', 'pro_nombre' => 'Chota', 'dep_id' => '06'],
            ['pro_id' => '0605', 'pro_nombre' => 'Contumazá', 'dep_id' => '06'],
            ['pro_id' => '0606', 'pro_nombre' => 'Cutervo', 'dep_id' => '06'],
            ['pro_id' => '0607', 'pro_nombre' => 'Hualgayoc', 'dep_id' => '06'],
            ['pro_id' => '0608', 'pro_nombre' => 'Jaén', 'dep_id' => '06'],
            ['pro_id' => '0609', 'pro_nombre' => 'San Ignacio', 'dep_id' => '06'],
            ['pro_id' => '0610', 'pro_nombre' => 'San Marcos', 'dep_id' => '06'],
            ['pro_id' => '0611', 'pro_nombre' => 'San Miguel', 'dep_id' => '06'],
            ['pro_id' => '0612', 'pro_nombre' => 'San Pablo', 'dep_id' => '06'],
            ['pro_id' => '0613', 'pro_nombre' => 'Santa Cruz', 'dep_id' => '06'],
            ['pro_id' => '0701', 'pro_nombre' => 'Prov. Const. del Callao', 'dep_id' => '07'],
            ['pro_id' => '0801', 'pro_nombre' => 'Cusco', 'dep_id' => '08'],
            ['pro_id' => '0802', 'pro_nombre' => 'Acomayo', 'dep_id' => '08'],
            ['pro_id' => '0803', 'pro_nombre' => 'Anta', 'dep_id' => '08'],
            ['pro_id' => '0804', 'pro_nombre' => 'Calca', 'dep_id' => '08'],
            ['pro_id' => '0805', 'pro_nombre' => 'Canas', 'dep_id' => '08'],
            ['pro_id' => '0806', 'pro_nombre' => 'Canchis', 'dep_id' => '08'],
            ['pro_id' => '0807', 'pro_nombre' => 'Chumbivilcas', 'dep_id' => '08'],
            ['pro_id' => '0808', 'pro_nombre' => 'Espinar', 'dep_id' => '08'],
            ['pro_id' => '0809', 'pro_nombre' => 'La Convención', 'dep_id' => '08'],
            ['pro_id' => '0810', 'pro_nombre' => 'Paruro', 'dep_id' => '08'],
            ['pro_id' => '0811', 'pro_nombre' => 'Paucartambo', 'dep_id' => '08'],
            ['pro_id' => '0812', 'pro_nombre' => 'Quispicanchi', 'dep_id' => '08'],
            ['pro_id' => '0813', 'pro_nombre' => 'Urubamba', 'dep_id' => '08'],
            ['pro_id' => '0901', 'pro_nombre' => 'Huancavelica', 'dep_id' => '09'],
            ['pro_id' => '0902', 'pro_nombre' => 'Acobamba', 'dep_id' => '09'],
            ['pro_id' => '0903', 'pro_nombre' => 'Angaraes', 'dep_id' => '09'],
            ['pro_id' => '0904', 'pro_nombre' => 'Castrovirreyna', 'dep_id' => '09'],
            ['pro_id' => '0905', 'pro_nombre' => 'Churcampa', 'dep_id' => '09'],
            ['pro_id' => '0906', 'pro_nombre' => 'Huaytará', 'dep_id' => '09'],
            ['pro_id' => '0907', 'pro_nombre' => 'Tayacaja', 'dep_id' => '09'],
            ['pro_id' => '1001', 'pro_nombre' => 'Huánuco', 'dep_id' => '10'],
            ['pro_id' => '1002', 'pro_nombre' => 'Ambo', 'dep_id' => '10'],
            ['pro_id' => '1003', 'pro_nombre' => 'Dos de Mayo', 'dep_id' => '10'],
            ['pro_id' => '1004', 'pro_nombre' => 'Huacaybamba', 'dep_id' => '10'],
            ['pro_id' => '1005', 'pro_nombre' => 'Huamalíes', 'dep_id' => '10'],
            ['pro_id' => '1006', 'pro_nombre' => 'Leoncio Prado', 'dep_id' => '10'],
            ['pro_id' => '1007', 'pro_nombre' => 'Marañón', 'dep_id' => '10'],
            ['pro_id' => '1008', 'pro_nombre' => 'Pachitea', 'dep_id' => '10'],
            ['pro_id' => '1009', 'pro_nombre' => 'Puerto Inca', 'dep_id' => '10'],
            ['pro_id' => '1010', 'pro_nombre' => 'Lauricocha ', 'dep_id' => '10'],
            ['pro_id' => '1011', 'pro_nombre' => 'Yarowilca ', 'dep_id' => '10'],
            ['pro_id' => '1101', 'pro_nombre' => 'Ica ', 'dep_id' => '11'],
            ['pro_id' => '1102', 'pro_nombre' => 'Chincha ', 'dep_id' => '11'],
            ['pro_id' => '1103', 'pro_nombre' => 'Nasca ', 'dep_id' => '11'],
            ['pro_id' => '1104', 'pro_nombre' => 'Palpa ', 'dep_id' => '11'],
            ['pro_id' => '1105', 'pro_nombre' => 'Pisco ', 'dep_id' => '11'],
            ['pro_id' => '1201', 'pro_nombre' => 'Huancayo ', 'dep_id' => '12'],
            ['pro_id' => '1202', 'pro_nombre' => 'Concepción ', 'dep_id' => '12'],
            ['pro_id' => '1203', 'pro_nombre' => 'Chanchamayo ', 'dep_id' => '12'],
            ['pro_id' => '1204', 'pro_nombre' => 'Jauja ', 'dep_id' => '12'],
            ['pro_id' => '1205', 'pro_nombre' => 'Junín ', 'dep_id' => '12'],
            ['pro_id' => '1206', 'pro_nombre' => 'Satipo ', 'dep_id' => '12'],
            ['pro_id' => '1207', 'pro_nombre' => 'Tarma ', 'dep_id' => '12'],
            ['pro_id' => '1208', 'pro_nombre' => 'Yauli ', 'dep_id' => '12'],
            ['pro_id' => '1209', 'pro_nombre' => 'Chupaca ', 'dep_id' => '12'],
            ['pro_id' => '1301', 'pro_nombre' => 'Trujillo ', 'dep_id' => '13'],
            ['pro_id' => '1302', 'pro_nombre' => 'Ascope ', 'dep_id' => '13'],
            ['pro_id' => '1303', 'pro_nombre' => 'Bolívar ', 'dep_id' => '13'],
            ['pro_id' => '1304', 'pro_nombre' => 'Chepén ', 'dep_id' => '13'],
            ['pro_id' => '1305', 'pro_nombre' => 'Julcán ', 'dep_id' => '13'],
            ['pro_id' => '1306', 'pro_nombre' => 'Otuzco ', 'dep_id' => '13'],
            ['pro_id' => '1307', 'pro_nombre' => 'Pacasmayo ', 'dep_id' => '13'],
            ['pro_id' => '1308', 'pro_nombre' => 'Pataz ', 'dep_id' => '13'],
            ['pro_id' => '1309', 'pro_nombre' => 'Sánchez Carrión ', 'dep_id' => '13'],
            ['pro_id' => '1310', 'pro_nombre' => 'Santiago de Chuco ', 'dep_id' => '13'],
            ['pro_id' => '1311', 'pro_nombre' => 'Gran Chimú ', 'dep_id' => '13'],
            ['pro_id' => '1312', 'pro_nombre' => 'Virú ', 'dep_id' => '13'],
            ['pro_id' => '1401', 'pro_nombre' => 'Chiclayo ', 'dep_id' => '14'],
            ['pro_id' => '1402', 'pro_nombre' => 'Ferreñafe ', 'dep_id' => '14'],
            ['pro_id' => '1403', 'pro_nombre' => 'Lambayeque ', 'dep_id' => '14'],
            ['pro_id' => '1501', 'pro_nombre' => 'Lima ', 'dep_id' => '15'],
            ['pro_id' => '1502', 'pro_nombre' => 'Barranca ', 'dep_id' => '15'],
            ['pro_id' => '1503', 'pro_nombre' => 'Cajatambo ', 'dep_id' => '15'],
            ['pro_id' => '1504', 'pro_nombre' => 'Canta ', 'dep_id' => '15'],
            ['pro_id' => '1505', 'pro_nombre' => 'Cañete ', 'dep_id' => '15'],
            ['pro_id' => '1506', 'pro_nombre' => 'Huaral ', 'dep_id' => '15'],
            ['pro_id' => '1507', 'pro_nombre' => 'Huarochirí ', 'dep_id' => '15'],
            ['pro_id' => '1508', 'pro_nombre' => 'Huaura ', 'dep_id' => '15'],
            ['pro_id' => '1509', 'pro_nombre' => 'Oyón ', 'dep_id' => '15'],
            ['pro_id' => '1510', 'pro_nombre' => 'Yauyos ', 'dep_id' => '15'],
            ['pro_id' => '1601', 'pro_nombre' => 'Maynas ', 'dep_id' => '16'],
            ['pro_id' => '1602', 'pro_nombre' => 'Alto Amazonas ', 'dep_id' => '16'],
            ['pro_id' => '1603', 'pro_nombre' => 'Loreto ', 'dep_id' => '16'],
            ['pro_id' => '1604', 'pro_nombre' => 'Mariscal Ramón Castilla ', 'dep_id' => '16'],
            ['pro_id' => '1605', 'pro_nombre' => 'Requena ', 'dep_id' => '16'],
            ['pro_id' => '1606', 'pro_nombre' => 'Ucayali ', 'dep_id' => '16'],
            ['pro_id' => '1607', 'pro_nombre' => 'Datem del Marañón ', 'dep_id' => '16'],
            ['pro_id' => '1608', 'pro_nombre' => 'Putumayo', 'dep_id' => '16'],
            ['pro_id' => '1701', 'pro_nombre' => 'Tambopata ', 'dep_id' => '17'],
            ['pro_id' => '1702', 'pro_nombre' => 'Manu ', 'dep_id' => '17'],
            ['pro_id' => '1703', 'pro_nombre' => 'Tahuamanu ', 'dep_id' => '17'],
            ['pro_id' => '1801', 'pro_nombre' => 'Mariscal Nieto ', 'dep_id' => '18'],
            ['pro_id' => '1802', 'pro_nombre' => 'General Sánchez Cerro ', 'dep_id' => '18'],
            ['pro_id' => '1803', 'pro_nombre' => 'Ilo ', 'dep_id' => '18'],
            ['pro_id' => '1901', 'pro_nombre' => 'Pasco ', 'dep_id' => '19'],
            ['pro_id' => '1902', 'pro_nombre' => 'Daniel Alcides Carrión ', 'dep_id' => '19'],
            ['pro_id' => '1903', 'pro_nombre' => 'Oxapampa ', 'dep_id' => '19'],
            ['pro_id' => '2001', 'pro_nombre' => 'Piura ', 'dep_id' => '20'],
            ['pro_id' => '2002', 'pro_nombre' => 'Ayabaca ', 'dep_id' => '20'],
            ['pro_id' => '2003', 'pro_nombre' => 'Huancabamba ', 'dep_id' => '20'],
            ['pro_id' => '2004', 'pro_nombre' => 'Morropón ', 'dep_id' => '20'],
            ['pro_id' => '2005', 'pro_nombre' => 'Paita ', 'dep_id' => '20'],
            ['pro_id' => '2006', 'pro_nombre' => 'Sullana ', 'dep_id' => '20'],
            ['pro_id' => '2007', 'pro_nombre' => 'Talara ', 'dep_id' => '20'],
            ['pro_id' => '2008', 'pro_nombre' => 'Sechura ', 'dep_id' => '20'],
            ['pro_id' => '2101', 'pro_nombre' => 'Puno ', 'dep_id' => '21'],
            ['pro_id' => '2102', 'pro_nombre' => 'Azángaro ', 'dep_id' => '21'],
            ['pro_id' => '2103', 'pro_nombre' => 'Carabaya ', 'dep_id' => '21'],
            ['pro_id' => '2104', 'pro_nombre' => 'Chucuito ', 'dep_id' => '21'],
            ['pro_id' => '2105', 'pro_nombre' => 'El Collao ', 'dep_id' => '21'],
            ['pro_id' => '2106', 'pro_nombre' => 'Huancané ', 'dep_id' => '21'],
            ['pro_id' => '2107', 'pro_nombre' => 'Lampa ', 'dep_id' => '21'],
            ['pro_id' => '2108', 'pro_nombre' => 'Melgar ', 'dep_id' => '21'],
            ['pro_id' => '2109', 'pro_nombre' => 'Moho ', 'dep_id' => '21'],
            ['pro_id' => '2110', 'pro_nombre' => 'San Antonio de Putina ', 'dep_id' => '21'],
            ['pro_id' => '2111', 'pro_nombre' => 'San Román ', 'dep_id' => '21'],
            ['pro_id' => '2112', 'pro_nombre' => 'Sandia ', 'dep_id' => '21'],
            ['pro_id' => '2113', 'pro_nombre' => 'Yunguyo ', 'dep_id' => '21'],
            ['pro_id' => '2201', 'pro_nombre' => 'Moyobamba ', 'dep_id' => '22'],
            ['pro_id' => '2202', 'pro_nombre' => 'Bellavista ', 'dep_id' => '22'],
            ['pro_id' => '2203', 'pro_nombre' => 'El Dorado ', 'dep_id' => '22'],
            ['pro_id' => '2204', 'pro_nombre' => 'Huallaga ', 'dep_id' => '22'],
            ['pro_id' => '2205', 'pro_nombre' => 'Lamas ', 'dep_id' => '22'],
            ['pro_id' => '2206', 'pro_nombre' => 'Mariscal Cáceres ', 'dep_id' => '22'],
            ['pro_id' => '2207', 'pro_nombre' => 'Picota ', 'dep_id' => '22'],
            ['pro_id' => '2208', 'pro_nombre' => 'Rioja ', 'dep_id' => '22'],
            ['pro_id' => '2209', 'pro_nombre' => 'San Martín ', 'dep_id' => '22'],
            ['pro_id' => '2210', 'pro_nombre' => 'Tocache ', 'dep_id' => '22'],
            ['pro_id' => '2301', 'pro_nombre' => 'Tacna ', 'dep_id' => '23'],
            ['pro_id' => '2302', 'pro_nombre' => 'Candarave ', 'dep_id' => '23'],
            ['pro_id' => '2303', 'pro_nombre' => 'Jorge Basadre ', 'dep_id' => '23'],
            ['pro_id' => '2304', 'pro_nombre' => 'Tarata ', 'dep_id' => '23'],
            ['pro_id' => '2401', 'pro_nombre' => 'Tumbes ', 'dep_id' => '24'],
            ['pro_id' => '2402', 'pro_nombre' => 'Contralmirante Villar ', 'dep_id' => '24'],
            ['pro_id' => '2403', 'pro_nombre' => 'Zarumilla ', 'dep_id' => '24'],
            ['pro_id' => '2501', 'pro_nombre' => 'Coronel Portillo ', 'dep_id' => '25'],
            ['pro_id' => '2502', 'pro_nombre' => 'Atalaya ', 'dep_id' => '25'],
            ['pro_id' => '2503', 'pro_nombre' => 'Padre Abad ', 'dep_id' => '25'],
            ['pro_id' => '2504', 'pro_nombre' => 'Purús', 'dep_id' => '25']
        ];

        foreach ($provinces as &$province) {
            $province['created_at'] = $currentTimestamp;
            $province['updated_at'] = $currentTimestamp;
        }

        Province::insert($provinces);
    }
}
